# Generated by Django 3.1.7 on 2021-04-12 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создаения'),
        ),
        migrations.AddField(
            model_name='course',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AddField(
            model_name='courselesson',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создаения'),
        ),
        migrations.AddField(
            model_name='courselesson',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AddField(
            model_name='coursetheme',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создаения'),
        ),
        migrations.AddField(
            model_name='coursetheme',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AddField(
            model_name='lessonfragment',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='lessonfragment',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создаения'),
        ),
    ]
