# Generated by Django 3.1.7 on 2021-04-13 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20210412_1947'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessonfragment',
            options={'ordering': ('id',), 'verbose_name': 'Фрагмент урока', 'verbose_name_plural': 'Фрагменты урока'},
        ),
    ]
