# Generated by Django 3.1.7 on 2021-06-16 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20210517_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courselesson',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Описание урока'),
        ),
    ]
