# Generated by Django 3.1.7 on 2021-04-14 07:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210413_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_reviewers',
            field=models.ManyToManyField(blank=True, related_name='reviewers_set', related_query_name='reviewers', to=settings.AUTH_USER_MODEL, verbose_name='Ревьюеры пользователя'),
        ),
    ]
