# Generated by Django 3.1.7 on 2021-06-07 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210601_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_notifications',
            field=models.BooleanField(default=True, verbose_name='Уведомления на почту'),
        ),
    ]
