# Generated by Django 3.1.7 on 2021-06-19 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210607_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='github_url',
        ),
        migrations.AddField(
            model_name='user',
            name='repl_it_username',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Юзернейм на repl.it'),
        ),
    ]
