# Generated by Django 3.1.7 on 2021-04-17 07:05

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210415_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=sorl.thumbnail.fields.ImageField(default='static/default_avatar.jpg', upload_to='avatars', verbose_name='Фотография'),
        ),
    ]
