stages:
  - deploy

deploy:dev:
  stage: deploy
  image: ubuntu
  tags:
    - course-platform
  before_script:
    - apt-get update && apt-get -y install openssh-server
    - mkdir -p ~/.ssh
    # Paste the PRIVATE key into a gitlab variable. Pay attention to the linebreak at the end when pasting
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 700 ~/.ssh/id_rsa
    - eval "$(ssh-agent -s)"
    - ssh-add ~/.ssh/id_rsa
    - ssh-keyscan -H 45.80.68.123 >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - ssh root@45.80.68.123 -p 22
      "
        cd ${PROJECT_ROOT} &&
        cd ci/ &&
        docker-compose down
      "
  only:
    - dev
