stages:
  - deploy

# Переменные необходимые для этой job
# - SERVER_USER
# - SERVER_HOST
# - SERVER_PORT
# - SERVER_SSH_PRIVATE_KEY
deploy:dev:
  stage: deploy
  image: ubuntu
  tags:
    - course-platform
  before_script:
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

  script:
    - echo 'hello world'
    - ls -a
#    - ssh -tt $SERVER_USER@$SERVER_HOST -p $SERVER_PORT
#      "
#      cd ${PROJECT_ROOT} &&
#      git reset --hard &&
#      git checkout master &&
#      git pull --recurse-submodules &&
#      cd ci/dev &&
#      export APP_BOT_TOKEN=$BOT_TOKEN &&
#      export FRONTEND_MODE=start &&
#      docker-compose -f docker-compose.yml -f docker-compose.dev.yml up -d --remove-orphans --build &&
#      docker-compose -f docker-compose.yml -f docker-compose.dev.yml restart &&
#      "
  only:
    - dev