# Generated by Django 3.1.7 on 2021-05-03 06:37

from django.db import migrations, models
import files.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('content', models.FileField(upload_to=files.utils.upload_path, verbose_name='Файл')),
            ],
        ),
    ]
