# Generated by Django 3.1.7 on 2021-06-07 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_file_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Название файла'),
        ),
        migrations.AddField(
            model_name='file',
            name='type',
            field=models.PositiveIntegerField(choices=[(1, 'Файл'), (2, 'Изображение'), (3, 'Остальное')], default=3, verbose_name='Тип файла'),
        ),
    ]
