# Generated by Django 3.1.7 on 2021-06-12 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_coursefile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursefile',
            name='user',
        ),
    ]
