# Generated by Django 3.1.7 on 2021-03-23 19:07

from django.db import migrations, models
import django.db.models.deletion
import martor.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=130, verbose_name='Название курса')),
                ('description', models.TextField(blank=True, max_length=1200, null=True, verbose_name='Описание курса')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Стоимость курса')),
            ],
        ),
        migrations.CreateModel(
            name='CourseBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=130, verbose_name='Название учебного блока')),
                ('description', models.TextField(blank=True, max_length=1200, null=True, verbose_name='Описание учебного блока')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='CourseBlockLesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=130, verbose_name='Название урока')),
                ('description', martor.models.MartorField()),
                ('course_block', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.courseblock')),
            ],
        ),
    ]
