# Generated by Django 3.1.7 on 2021-04-01 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursetheme',
            name='free_access',
            field=models.BooleanField(default=False, verbose_name='Бесплатный доступ'),
        ),
    ]
