# Generated by Django 3.1.7 on 2021-03-26 06:25

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20210324_1955'),
    ]

    operations = [
        migrations.CreateModel(
            name='CTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_test_field', markdownx.models.MarkdownxField()),
            ],
        ),
    ]
