# Generated by Django 3.1.7 on 2021-04-01 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_courselesson_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonfragment',
            name='date_created',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата создаения фрагмента'),
        ),
    ]
