# Generated by Django 3.1.7 on 2021-03-24 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20210324_1955'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.CreateModel(
            name='CourseBlockLessonAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Заблокирован'), (2, 'Доступен'), (3, 'В процессе'), (4, 'Завершен')], verbose_name='Статус')),
                ('progress', models.DecimalField(decimal_places=2, default='0.00', max_digits=3, verbose_name='Прогресс')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.courseblocklesson')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CourseBlockAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Заблокирован'), (2, 'Доступен'), (3, 'В процессе'), (4, 'Завершен')], verbose_name='Статус')),
                ('progress', models.DecimalField(decimal_places=2, default='0.00', max_digits=3, verbose_name='Прогресс')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.courseblock')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CourseAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Заблокирован'), (2, 'Доступен'), (3, 'В процессе'), (4, 'Завершен')], verbose_name='Статус')),
                ('progress', models.DecimalField(decimal_places=2, default='0.00', max_digits=3, verbose_name='Прогресс')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='user',
            name='user_access_course',
            field=models.ManyToManyField(blank=True, related_name='user_access_course_set', related_query_name='user_access_course', to='users.CourseAccess', verbose_name='Доступные курсы для пользователя'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_access_course_block',
            field=models.ManyToManyField(blank=True, related_name='user_access_course_block_set', related_query_name='user_access_course_block', to='users.CourseBlockAccess', verbose_name='Доступные блоки уроков для пользователя'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_access_course_block_lesson',
            field=models.ManyToManyField(blank=True, related_name='user_access_course_block_lesson_set', related_query_name='user_access_course_block_lesson', to='users.CourseBlockLessonAccess', verbose_name='Доступные уроки для пользователя'),
        ),
    ]
