# Generated by Django 3.1.7 on 2021-04-10 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Доступен'), (2, 'В процессе'), (3, 'Завершен'), (4, 'Заблокирован')], default=4, verbose_name='Статус')),
                ('date_created', models.DateTimeField(auto_now=True, verbose_name='Дата создаения фрагмента')),
                ('access_type', models.PositiveSmallIntegerField(choices=[(1, 'Пробный доступ'), (2, 'Оплаченный доступ'), (3, 'Полный неоплаченный доступ')], default=1, verbose_name='Тип доступа')),
            ],
            options={
                'verbose_name': 'Доступ к курсу',
                'verbose_name_plural': 'Доступ к курсам',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CourseLessonAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Доступен'), (2, 'В процессе'), (3, 'Завершен'), (4, 'Заблокирован')], default=4, verbose_name='Статус')),
                ('date_created', models.DateTimeField(auto_now=True, verbose_name='Дата создаения фрагмента')),
            ],
            options={
                'verbose_name': 'Доступ к уроку',
                'verbose_name_plural': 'Доступ к урокам',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CourseThemeAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Доступен'), (2, 'В процессе'), (3, 'Завершен'), (4, 'Заблокирован')], default=4, verbose_name='Статус')),
                ('date_created', models.DateTimeField(auto_now=True, verbose_name='Дата создаения фрагмента')),
            ],
            options={
                'verbose_name': 'Доступ к теме курса',
                'verbose_name_plural': 'Доступ к темам курса',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LessonFragmentAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Доступен'), (2, 'В процессе'), (3, 'Завершен'), (4, 'Заблокирован')], default=4, verbose_name='Статус')),
                ('date_created', models.DateTimeField(auto_now=True, verbose_name='Дата создаения фрагмента')),
                ('lesson_fragment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.lessonfragment')),
            ],
            options={
                'verbose_name': 'Доступ к фрагменту урока',
                'verbose_name_plural': 'Доступ к фрагментам урока',
                'abstract': False,
            },
        ),
    ]
