# Generated by Django 3.1.7 on 2021-05-03 06:37

import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('date_completed', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Доступен'), (2, 'В процессе'), (3, 'Завершен'), (4, 'Заблокирован')], default=4, verbose_name='Статус')),
                ('access_type', models.PositiveSmallIntegerField(choices=[(1, 'Пробный доступ'), (2, 'Оплаченный доступ'), (3, 'Полный неоплаченный доступ'), (4, 'Без доступа')], default=1, verbose_name='Тип доступа')),
                ('block_reason', models.PositiveIntegerField(blank=True, choices=[(1, 'За сутки было пройдено две темы курса')], null=True, verbose_name='Причина блокировки')),
                ('course_theme', models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='Доступы к темам')),
                ('course_lesson', models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='Доступы к урокам')),
                ('lesson_fragment', models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='Доступы к фрагментам')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
            ],
        ),
    ]
