# Generated by Django 3.1.7 on 2021-04-10 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_access', '0002_auto_20210410_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseaccess',
            name='access_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Пробный доступ'), (2, 'Оплаченный доступ'), (3, 'Полный неоплаченный доступ'), (4, 'Без доступа')], default=1, verbose_name='Тип доступа'),
        ),
    ]
