# Generated by Django 3.1.7 on 2021-05-08 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses_access', '0002_access_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='access',
            options={'verbose_name': 'Доступ к учебным материалам', 'verbose_name_plural': 'Доступы к учебным материалам'},
        ),
    ]
