# Generated by Django 3.1.7 on 2021-05-10 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('courses_access', '0003_auto_20210508_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='access',
            name='manual_access',
            field=models.ManyToManyField(blank=True, help_text='Укажите уроки, у которые будут доступны пользователю вместе с темой', related_name='manual_access_set', to='courses.CourseLesson', verbose_name='Ручной доступ к уроку'),
        ),
    ]
