# Generated by Django 3.1.7 on 2021-04-14 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_access', '0004_auto_20210414_0735'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseaccess',
            name='block_reason',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'За сутки было пройдено две темы курса')], null=True, verbose_name='Причина блокировки'),
        ),
        migrations.AddField(
            model_name='courselessonaccess',
            name='block_reason',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'За сутки было пройдено две темы курса')], null=True, verbose_name='Причина блокировки'),
        ),
        migrations.AddField(
            model_name='coursethemeaccess',
            name='block_reason',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'За сутки было пройдено две темы курса')], null=True, verbose_name='Причина блокировки'),
        ),
        migrations.AddField(
            model_name='lessonfragmentaccess',
            name='block_reason',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'За сутки было пройдено две темы курса')], null=True, verbose_name='Причина блокировки'),
        ),
    ]
