version: '3.7'

services:

  # ####################################################################################################################
  # Веб-сервисы (backend)
  # ####################################################################################################################
  backend:
    depends_on:
      - psql
      - redis
    ports:
      - $BACKEND_EXT_PORT:8000

  psql:
    image: postgres:11-alpine
    expose:
      - 5432
    volumes:
      - "psql_data:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: ${PSQL_USER}
      POSTGRES_PASSWORD: ${PSQL_PASS}
      POSTGRES_DB: ${PSQL_DB}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${PSQL_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    expose:
      - 6379
    volumes:
      - "redis_data:/data"
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli", "ping" ]
      interval: 1s
      timeout: 3s
      retries: 30

volumes:
  psql_data: {}
  redis_data: {}
