version: '3.7'

services:

  # ####################################################################################################################
  # Веб-сервисы (backend)
  # ####################################################################################################################
  backend:
    depends_on:
      - psql
      - redis
    ports:
      - $BACKEND_EXT_PORT:8000

  psql:
    image: postgres:11-alpine
    restart: on-failure
    expose:
      - 5432
    volumes:
      - "psql_data:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: ${PSQL_USER}
      POSTGRES_PASSWORD: ${PSQL_PASS}
      POSTGRES_DB: ${PSQL_DB}

  redis:
    image: redis:alpine
    restart: on-failure
    expose:
      - 6379
    volumes:
      - "redis_data:/data"

volumes:
  psql_data: {}
  redis_data: {}
