version: '3.7'

x-backend-env:
  &backend-env
    APP_MODE: ${APP_MODE}
    DATABASE_URL: 'psql://${PSQL_USER}:${PSQL_PASS}@psql:5432/${PSQL_DB}'
    DEBUG: ${APP_DEBUG}
    BASE_FRONT_URL: ${BASE_FRONT_URL}
    BASE_URL: ${BASE_URL}
    REDIS_URL: 'redis://redis:6379/1'
    DJANGO_LOG_LEVEL: ${DJANGO_LOG_LEVEL}
    SENTRY_DSN: ${SENTRY_DSN}

    MAILGUN_TOKEN: ${MAILGUN_TOKEN}
    MAILGUN_HOST: ${MAILGUN_HOST}
    DEFAULT_FROM_EMAIL: ${DEFAULT_FROM_EMAIL}
    DEFAULT_ADMIN_EMAIL: ${DEFAULT_ADMIN_EMAIL}

    TINKOFF_URL: 'https://securepay.tinkoff.ru/v2/'
    TINKOFF_TERMINAL_KEY: ${TINKOFF_TERMINAL_KEY}
    TINKOFF_TERMINAL_PASSWORD: ${TINKOFF_TERMINAL_PASSWORD}

    TINKOFF_CREDIT_URL: 'https://forma.tinkoff.ru/api/partners/v2/'
    TINKOFF_CREDIT_SHOP_ID: ${TINKOFF_CREDIT_SHOP_ID}
    TINKOFF_CREDIT_SHOWCASE_ID: ${TINKOFF_CREDIT_SHOWCASE_ID}

x-backend:
  &backend
  build:
    context: ../
    dockerfile: ci/docker/backend/Dockerfile
  restart: on-failure
  tty: true
  volumes:
    - "../app/backend/:/var/app"
  environment:
    <<: *backend-env


services:

  # ####################################################################################################################
  # Веб-сервисы (backend)
  # ####################################################################################################################
  backend:
    <<: *backend

  frontend:
    build:
      context: ../
      dockerfile: ci/docker/frontend/Dockerfile
    restart: on-failure
    volumes:
      - "../app/frontend/:/var/app"
    environment:
      BASE_URL: ${BASE_URL}
      SOCKET_URL: ${SOCKET_URL}

  asyns_tasks:
    <<: *backend
    command: >
      bash -c "
      dockerize -wait tcp://redis:6379
      celery -A crm worker --loglevel=DEBUG"
    depends_on:
      - backend