# Generated by Django 3.1.7 on 2021-04-19 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dialog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('users', models.ManyToManyField(blank=True, related_name='dialog_users_set', related_query_name='dialog_users', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи')),
            ],
        ),
        migrations.CreateModel(
            name='DialogMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', markdownx.models.MarkdownxField(blank=True, null=True, verbose_name='Сообщение')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправления')),
                ('date_read', models.DateTimeField(blank=True, null=True, verbose_name='Дата прочтения')),
                ('dialog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dialogs.dialog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date_created',),
            },
        ),
    ]
