# Generated by Django 3.1.7 on 2021-05-03 06:37

from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dialog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
            ],
        ),
        migrations.CreateModel(
            name='DialogMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', markdownx.models.MarkdownxField(blank=True, null=True, verbose_name='Сообщение')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправления')),
                ('date_read', models.DateTimeField(blank=True, null=True, verbose_name='Дата прочтения')),
                ('dialog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dialogs.dialog')),
            ],
            options={
                'ordering': ('date_created',),
            },
        ),
    ]
