# Generated by Django 3.1.7 on 2021-04-19 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
        ('dialogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialogmessage',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='files.file'),
        ),
    ]
