# Generated by Django 3.1.7 on 2021-05-03 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0001_initial'),
        ('courses', '0001_initial'),
        ('dialogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialogmessage',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='files.file'),
        ),
        migrations.AddField(
            model_name='dialogmessage',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.courselesson'),
        ),
    ]
