# Generated by Django 3.1.7 on 2021-05-03 06:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dialogs', '0002_auto_20210503_0937'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dialogmessage',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dialog',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='dialog_users_set', related_query_name='dialog_users', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи'),
        ),
    ]
