# Generated by Django 3.1.7 on 2021-06-01 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dialogs', '0003_auto_20210503_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialogmessage',
            name='dialog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dialogs.dialog'),
        ),
    ]
