# Generated by Django 3.1.7 on 2021-06-04 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialogs', '0004_auto_20210601_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialog',
            name='with_role',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Студент'), (2, 'Наставник'), (3, 'Педагог'), (4, 'Администратор'), (5, 'Поддержка')], null=True, verbose_name='Диалог с ролью'),
        ),
    ]
