# Generated by Django 3.1.7 on 2021-06-08 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dialogs', '0006_dialogmessage_reply_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dialogmessage',
            old_name='reply_id',
            new_name='reply',
        ),
    ]
