# Generated by Django 3.1.7 on 2021-06-16 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dicts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=120, verbose_name='Ключ')),
                ('value', models.CharField(max_length=300, verbose_name='Значение')),
            ],
        ),
    ]
