# Generated by Django 3.1.7 on 2021-06-19 10:15

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('dicts', '0002_dicts_description'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='dicts',
            managers=[
                ('defaults', django.db.models.manager.Manager()),
            ],
        ),
    ]
