# Generated by Django 3.1.7 on 2021-05-06 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма оплаты в копейках')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания платежки')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления платежки')),
                ('date_payment', models.DateTimeField(blank=True, null=True, verbose_name='Дата оплаты')),
                ('status', models.CharField(blank=True, choices=[('NEW', 'Создан'), ('FORM_SHOWED', 'Платежная форма открыта покупателем'), ('DEADLINE_EXPIRED', 'Просрочен'), ('CANCELED', 'Отменен'), ('PREAUTHORIZING', 'Проверка платежных данных'), ('AUTHORIZING', 'Резервируется'), ('AUTHORIZED', 'Зарезервирован'), ('AUTH_FAIL', 'Не прошел авторизацию'), ('REJECTED', 'Отклонен'), ('3DS_CHECKING', 'Проверяется по протоколу 3-D Secure'), ('3DS_CHECKED', 'Проверен по протоколу 3-D Secure'), ('REVERSING', 'Резервирование отменяется'), ('PARTIAL_REVERSED', 'Резервирование отменено частично'), ('REVERSED', 'Резервирование отменено'), ('CONFIRMING', 'Подтверждается'), ('CONFIRMED', 'Подтвержден'), ('REFUNDING', 'Возвращается'), ('PARTIAL_REFUNDED', 'Возвращен частично'), ('REFUNDED', 'Возвращен полностью')], max_length=21, null=True, verbose_name='Статус платежки')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
