# Generated by Django 3.1.7 on 2021-05-11 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20210511_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentcredit',
            name='promo_code',
            field=models.CharField(blank=True, choices=[('installment_0_0_4_5', '0-0-4'), ('installment_0_0_6_6', '0-0-6'), ('installment_0_0_10_10', '0-0-10'), ('installment_0_0_12_11', '0-0-12')], max_length=21, null=True, verbose_name='Тип кредитного продукта'),
        ),
    ]
