# Generated by Django 3.1.7 on 2021-05-12 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_paymentcredit_promo_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='external_payment_id',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='ID платежа во внешней системе'),
        ),
    ]
